site_name: Natural Language Processing - 2025s2

site_dir: build

nav:
  - Home: index.md
  - Sentiment Analysis:
    - 00 - Regular expressions: sentiment_analysis/00-regex.ipynb
    - 01 - Practice - Sentiment Analysis with ANEW: sentiment_analysis/01-handcrafted.md
    - 02 - Theory - Math of Logistic Regression: sentiment_analysis/02-math_of_lr.md
    - 03 - Case Study - Classification on IMDB: sentiment_analysis/03-case_study_sentiment.ipynb
    - 04 - Practice - Cross-dataset Classification: sentiment_analysis/04-studio-cross_dataset.ipynb
    - 05 - Practice - Detecting Fake News: sentiment_analysis/05-detecting_fake_news.md
  - Language Models:
    - 00 - Theory - Language Models: language_models/00-language_models_ngrams.ipynb
    - 01 - Case Study - Language Models: language_models/01-case_study_bullshit.ipynb
    - 02 - Theory - From Sklearn to Pytorch: language_models/02-from_sklearn_to_pytorch.ipynb
    - 03 - Theory - Tokenizers: language_models/03-end_to_end_neural_networks.ipynb
    - 04 - Theory - Self-attention: language_models/04-self_attention.ipynb
    - 05 - Theory - Multiple layers: language_models/05-mlp.ipynb
    - 06 - Case Study - Pre-trained BERT: language_models/06-pretrained_bert.ipynb
#    - 07 - Practice - Fine-tuning BERT: language_models/07-fine_tuning_bert.ipynb

theme:
  name: mkdocs
  features:
    - content.mathjax

markdown_extensions:
  - mdx_math:
      enable_dollar_delimiter: true 
      add_preview: true

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


plugins:
  - search
  - mermaid2

  - mkdocs-jupyter:
      ignore_h1_titles: True
      theme: mkdocs



extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
  - https://unpkg.com/mermaid/dist/mermaid.min.js
