site_name: Natural Language Processing - 2025s2

site_dir: build

nav:
  - Home: index.md
  - Final Project: final_project.md
  - Text Classification:
    - 00 - Review - Regular expressions: text_classification/00-regex.ipynb
    - 01 - Practice - Sentiment Analysis with ANEW: text_classification/01-handcrafted.md
    - 02 - Theory - Math of Logistic Regression: text_classification/02-math_of_lr.md
    - 02a - Theory - Supplementary Material: text_classification/02a-toy_problem.ipynb
    - 03 - Case Study - Classification on IMDB: text_classification/03-case_study_sentiment.ipynb
    - 04 - Practice - Cross-dataset Classification: text_classification/04-studio-cross-dataset.md
    - 05 - Practice - Detecting Fake News: text_classification/05-detecting_fake_news.md
  - Language Models:
    - 00 - Theory - Language Models: language_models/00-language_models_ngrams.ipynb
    - 00a - Solution for exercises in 00: language_models/00a-solutions.ipynb
    - 01 - Case Study - Language Models: language_models/01-case_study_bullshit.ipynb
    - 02 - Theory - From Sklearn to Pytorch: language_models/02-from_sklearn_to_pytorch.ipynb
    - 03 - Theory - MLP, Residuals, Normalization: language_models/05-mlp.ipynb
    - 05 - Practice - Tokenizers, Classification and Visualization: language_models/03-end_to_end_neural_networks.ipynb
    - 06 - Theory - Self-Attention and Self-Supervised Training: language_models/04-self_attention.ipynb
    - 07 - Case Study - Pre-trained BERT: language_models/06-pretrained_bert.ipynb
    - 08 - Practice - Fine-tuning BERT: language_models/07-finetuning_bert.ipynb

theme:
  name: mkdocs
  features:
    - content.mathjax

markdown_extensions:
  - mdx_math:
      enable_dollar_delimiter: true 
      add_preview: true

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


plugins:
  - search
  - mermaid2

  - mkdocs-jupyter:
      ignore_h1_titles: True
      theme: mkdocs



extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
  - https://unpkg.com/mermaid/dist/mermaid.min.js
